---
bibliography: bio.bib
csl: harvard-cite-them-right.csl
title: Group Name's Group Project
execute:
  echo: false
format:
  html:
    theme:
      - minty
      - css/web.scss
    code-copy: true
    code-link: true
    toc: true
    toc-title: On this page
    toc-depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    mainfont: Spectral
    sansfont: Roboto
    monofont: JetBrainsMono-Regular
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: false
    colorlinks: true
    highlight-style: github
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

## Declaration of Authorship {.unnumbered .unlisted}

We, [insert your group's names], confirm that the work presented in this assessment is our own. Where information has been derived from other sources, we confirm that this has been indicated in the work. Where a Large Language Model such as ChatGPT has been used we confirm that we have made its contribution to the final submission clear.

Date:

Student Numbers: 

## Brief Group Reflection

| What Went Well | What Was Challenging |
| -------------- | -------------------- |
| A              | B                    |
| C              | D                    |

## Priorities for Feedback

Are there any areas on which you would appreciate more detailed feedback if we're able to offer it?

```{=html}
<style type="text/css">
.duedate {
  border: dotted 2px red; 
  background-color: rgb(255, 235, 235);
  height: 50px;
  line-height: 50px;
  margin-left: 40px;
  margin-right: 40px
  margin-top: 10px;
  margin-bottom: 10px;
  color: rgb(150,100,100);
  text-align: center;
}
</style>
```

{{< pagebreak >}}

# Response to Questions

```{python}
import os
import pandas as pd
```

```{python}
host = 'https://orca.casa.ucl.ac.uk'
path = '~jreades/data'
file = '2022-09-10-listings.csv.gz'
url  = f'{host}/{path}/{file}'

if os.path.exists(file):
  df = pd.read_csv(file, compression='gzip', low_memory=False)
else: 
  df = pd.read_csv(url, compression='gzip', low_memory=False)
  df.to_csv(file)
```

## 1. Who collected the data?

::: {.duedate}

( 2 points; Answer due Week 7 )
.

:


Inside Airbnb is an independent research project involving volunteers and researchers who systematically collect detailed data about Airbnb listings. This data includes information such as the geographical location of listings, host details, pricing, customer reviews, and occupancy rates.

## 2. Why did they collect it?

::: {.duedate}

( 4 points; Answer due Week 7 )


The primary purpose of Inside Airbnb's data collection is to gain in-depth insights into the functioning of the Airbnb housing market and its impact on local housing markets and communities. The research aims to address questions related to hosts, rental pricing, property availability, market competition, and housing policies.

:::

```{python}
print(f"Data frame is {df.shape[0]:,} x {df.shape[1]:,}")
```

```{python}
ax = df.host_listings_count.plot.hist(bins=50);
ax.set_xlim([0,500]);
```

## 3. How was the data collected?  

::: {.duedate}

( 5 points; Answer due Week 8 )

Inside Airbnb mainly using web scraping and accessing Airbnb's Application Programming Interface (API) to compile information from publicly available listings on the Airbnb platform.
API Access: One common method is to access Airbnb's API, which provides structured and up-to-date data directly from Airbnb's servers.
Web Scraping: If API access is unavailable or does not provide the necessary data, web scraping can be used. Web scraping involves writing code to extract information from Airbnb's website. 
(Prentice, C. and Pawlicz, A., 2023)

:::

## 4. How does the method of collection impact the completeness and/or accuracy of its representation of the process it seeks to study, and what wider issues does this raise?

::: {.duedate}

( 11 points; Answer due Week 9 )

The Method of Collection Impacts Data Integrity and Accuracy: 

Since the data is collected from the Airbnb inside website, its completeness and accuracy depend on the information publicly available on the site. If certain details are not provided on the website, or if Airbnb changes its data format or structure, these details might not be captured accurately.(Alsudais, A., 2021)

Dynamism of Data: 

Information on the Airbnb website is dynamic, with listings constantly being added, removed, or modified. Inside Airbnb uses a web scraping method to periodically capture or update each listing, which could lead to data gaps or inaccuracies. Therefore, the timing of data collection affects accuracy, as it might not reflect these changes promptly.(Alsudais, A., 2021)

Broader Implications: 

Using data with errors can lead to erroneous conclusions. Making decisions based on these flawed results could have serious consequences. (Prentice, C. and Pawlicz, A., 2023）
:::

## 5. What ethical considerations does the use of this data raise? 

::: {.duedate}

( 18 points; Answer due {{< var assess.group-date >}} )

When analyzing the impact of COVID-19 on London's short-term rental market using internal Airbnb data, several ethical aspects must be considered:

#Quality and Integrity of Data: 

Ethically, it is essential to ensure the quality and integrity of the data used. Data sources in the sharing economy research may have limitations.(Prentice, C. and Pawlicz, A., 2023)  Due to privacy, competition, and/or regulatory factors, Airbnb and other STR platforms often hesitate to share their data. (Benítez-Aurioles, 2020)Researchers typically collect data directly from Airbnb.(von Briel, D. and Dolnicar, S., 2021) However, this web-scraped data can have inaccuracies or errors for various reasons, such as guests using different distribution channels or direct bookings, and listings being fraudulent, duplicates, inactive tests, or infrequently booked. (Adamiak, C., 2022)This practice could affect future research based on these studies and mislead practitioners relying on findings for commercial practices. (Prentice, C. and Pawlicz, A., 2023) Therefore, these limitations should be considered when interpreting and applying this data.

#Transparency and Reliability: 

The scientific method requires empirical evidence to validate hypotheses, making data collection and usage a vital part of science, supporting evidence-based decision-making. Computer scientists extensively use data for research and policy-making, including data obtained through illegal or unethical means. Some literature indicates that sharing and reusing existing datasets helps achieve repeatability,which is an important goal in science, but using such data can raise ethical and legal issues. (Thomas, D. R., Pastrana, S., Hutchings, A., Clayton, R., & Beresford, A. R. , 2017) Therefore, when presenting analysis results, it is necessary to ensure the transparency of the process, reliability of the results, and repeatability of the analysis. This includes clearly stating the data source, collection methods, and analysis process.

Fairness and Non-discrimination in Data Usage: When analyzing data, it is crucial to ensure that the data is not used for discriminatory or biased inferences.


:::

## 6. With reference to the data (*i.e.* using numbers, figures, maps, and descriptive statistics), what does an analysis of Hosts and Listing types suggest about the nature of Airbnb lets in London? 

::: {.duedate}

( 15 points; Answer due {{< var assess.group-date >}} )



:::

## 7. Drawing on your previous answers, and supporting your response with evidence (e.g. figures, maps, and statistical analysis/models), how *could* this data set be used to inform the regulation of Short-Term Lets (STL) in London? 

::: {.duedate}

( 45 points; Answer due {{< var assess.group-date >}} )

:::

## Sustainable Authorship Tools

Your QMD file should automatically download your BibTeX file. We will then re-run the QMD file to generate the output successfully.

Written in Markdown and generated from [Quarto](https://quarto.org/). Fonts used: [Spectral](https://fonts.google.com/specimen/Spectral) (mainfont), [Roboto](https://fonts.google.com/specimen/Roboto) (<span style="font-family:Sans-Serif;">sansfont</span>) and [JetBrains Mono](https://fonts.google.com/specimen/JetBrains%20Mono) (`monofont`). 

## References

```{python}

```
